
# dotnet core build

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self

trigger:
  batch: true
  branches:
    include:
    - master
    - dev

pr:
  branches:
    include:
    - master
    - dev

steps:

# restore
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    projects: '**/*.csproj'

# build
- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: build
    projects: '**/*.csproj'
    configuration: ${{ variables.buildConfiguration }}

# test and publish
- task: DotNetCoreCLI@2
  displayName: dotnet test
  continueOnError: true
  inputs:
    command: test
    projects: '**/*.csproj'
    configuration: ${{ variables.buildConfiguration }}

# publish
- task: DotNetCoreCLI@2
  displayName: dotnet publish
  inputs:
    command: publish
    projects: 'src/Dfc.ProviderPortal.FileProcessor.Functions/Dfc.ProviderPortal.FileProcessor.Functions.csproj'
    configuration: ${{ variables.buildConfiguration }}
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: false
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
     pathtoPublish: $(Build.ArtifactStagingDirectory)
     artifactName: Dfc.ProviderPortal.FileProcessor.Functions