# dotnet core build
pool:
  name: NCS - CI and CD

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'
  ArmTemplateRoot: '$(System.DefaultWorkingDirectory)\Resources\ArmTemplates'
  SolutionBaseName: 'Dfc.ProviderPortal.FileProcessor'
  GitVersionConfigFilePath: Resources/AzureDevOps/GitVersion.yml

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    endpoint: 'GitHub (ESFA)'
    ref: refs/tags/v1.11.2

trigger:
  batch: true
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

steps:

- task: UseGitVersion@5
  displayName: GitVersion
  inputs:
    useConfigFile: true
    configFilePath: ${{ variables.GitVersionConfigFilePath }}
    versionSpec: '5.3.x'


# ARM template
- template: AzureDevOpsTemplates\Build\StepTemplates\dfc-arm-build.yml@dfc-devops
  parameters:
    ArmTemplateRoot: '${{ variables.ArmTemplateRoot }}'
    SolutionBaseName: '${{ variables.SolutionBaseName }}'

# restore
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    projects: '**/*.csproj'

# build
- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: build
    projects: '**/*.csproj'
    configuration: ${{ variables.buildConfiguration }}

# test and publish
- task: DotNetCoreCLI@2
  displayName: dotnet test
  continueOnError: true
  inputs:
    command: test
    projects: '**/*.csproj'
    configuration: ${{ variables.buildConfiguration }}

# publish
- task: DotNetCoreCLI@2
  displayName: dotnet publish
  inputs:
    command: publish
    projects: 'src/Dfc.ProviderPortal.FileProcessor.Functions/Dfc.ProviderPortal.FileProcessor.Functions.csproj'
    configuration: ${{ variables.buildConfiguration }}
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: false
    zipAfterPublish: true

- task: CopyFiles@2
  displayName: 'Copy Azure folder to Staging'
  inputs:
    SourceFolder: $(System.DefaultWorkingDirectory)\Resources\ArmTemplates
    TargetFolder: $(build.artifactstagingdirectory)\Azure\Azure

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
     pathtoPublish: $(Build.ArtifactStagingDirectory)
     artifactName: Dfc.ProviderPortal.FileProcessor.Functions
